[10/07/2015 23:09:51] :: [base:handle_uncaught_exception:django.request] [256] :: Internal Server Error: /
Traceback (most recent call last):
  File "/home/chrysa/Bureau/42_work/framework/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chrysa/Bureau/42_work/framework/app/core/home.py", line 12, in index
    logger.info(info_load_log_message(request))
  File "/home/chrysa/Bureau/42_work/framework/app/generate_logs/functions.py", line 5, in info_load_log_message
    return 'chargement de la page ' + request.META['PATH_INFO'] + ' par ' + request.user
TypeError: Can't convert 'SimpleLazyObject' object to str implicitly
[10/07/2015 23:10:11] :: [base:handle_uncaught_exception:django.request] [256] :: Internal Server Error: /
Traceback (most recent call last):
  File "/home/chrysa/Bureau/42_work/framework/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chrysa/Bureau/42_work/framework/app/core/home.py", line 12, in index
    logger.info(info_load_log_message(request))
  File "/home/chrysa/Bureau/42_work/framework/app/generate_logs/functions.py", line 4, in info_load_log_message
    return 'chargement de la page ' + request.META['PATH_INFO'] + ' par ' + request.user
TypeError: Can't convert 'SimpleLazyObject' object to str implicitly
[10/07/2015 23:16:24] :: [base:handle_uncaught_exception:django.request] [256] :: Internal Server Error: /log/info/
Traceback (most recent call last):
  File "/home/chrysa/Bureau/42_work/framework/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chrysa/Bureau/42_work/framework/venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/chrysa/Bureau/42_work/framework/app/generate_logs/views.py", line 60, in display_log
    log.append(
AttributeError: 'NoneType' object has no attribute 'append'
